# configs/config.yaml
defaults:
  - train: train
  - data: data
  - _self_

# Model configs (loaded dynamically in train_all_models_and_ensemble)
model1_config: ${oc.load: configs/model/model1.yaml}
model2_config: ${oc.load: configs/model/model2.yaml}
model3_config: ${oc.load: configs/model/model3.yaml}

model_name: "model1"
debug: false
debug_samples: 100
run_full: false